#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT_DIR/credentials.local.env"
OUTPUT_FILE="$ROOT_DIR/pwa/.env.production.local"
RUN_BUILD="0"
TRIGGER_DEPLOY="0"
SET_GH="0"

usage() {
  cat <<'EOF'
Usage: setup-production-deploy.sh [options]

Options:
  --env-file <path>      Source env file (default: credentials.local.env)
  --output-file <path>   Target file (default: pwa/.env.production.local)
  --build                Run production build after writing env file
  --set-gh               Push required Variables/Secrets to GitHub repository
  --trigger-deploy       Trigger GitHub Actions deploy workflow
  -h, --help             Show this help

Examples:
  bash pwa/scripts/setup-production-deploy.sh
  bash pwa/scripts/setup-production-deploy.sh --set-gh
  bash pwa/scripts/setup-production-deploy.sh --build
  bash pwa/scripts/setup-production-deploy.sh --set-gh --build --trigger-deploy
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "[error] Missing required command: $1"
    exit 1
  fi
}

set_repo_variable() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "[skip] Variable $name empty"
    return
  fi
  gh variable set "$name" --body "$value"
  echo "[ok] Variable $name configured"
}

set_repo_secret() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "[skip] Secret $name empty"
    return
  fi
  gh secret set "$name" --body "$value"
  echo "[ok] Secret $name configured"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="$2"
      shift 2
      ;;
    --output-file)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --build)
      RUN_BUILD="1"
      shift
      ;;
    --set-gh)
      SET_GH="1"
      shift
      ;;
    --trigger-deploy)
      TRIGGER_DEPLOY="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[error] Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[error] Env file not found: $ENV_FILE"
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

VITE_BASE_URL_VALUE="${VITE_BASE_URL:-/MediTrace/}"
VITE_SUPABASE_URL_VALUE="${VITE_SUPABASE_URL:-}"
VITE_SUPABASE_PUBLISHABLE_KEY_VALUE="${VITE_SUPABASE_PUBLISHABLE_KEY:-}"
VITE_SUPABASE_REDIRECT_TO_VALUE="${VITE_SUPABASE_REDIRECT_TO:-}"

VITE_EMERGENCY_ADMIN_ENABLED_VALUE="${VITE_EMERGENCY_ADMIN_ENABLED:-0}"
VITE_EMERGENCY_ADMIN_USERNAME_VALUE="${VITE_EMERGENCY_ADMIN_USERNAME:-${MEDITRACE_EMERGENCY_ADMIN_USERNAME:-}}"
VITE_EMERGENCY_ADMIN_PASSWORD_VALUE="${VITE_EMERGENCY_ADMIN_PASSWORD:-${MEDITRACE_EMERGENCY_ADMIN_PASSWORD:-}}"
VITE_EMERGENCY_ADMIN_EMAIL_VALUE="${VITE_EMERGENCY_ADMIN_EMAIL:-${MEDITRACE_EMERGENCY_ADMIN_EMAIL:-}}"
VITE_EMERGENCY_ADMIN_FIRST_NAME_VALUE="${VITE_EMERGENCY_ADMIN_FIRST_NAME:-Admin}"
VITE_EMERGENCY_ADMIN_LAST_NAME_VALUE="${VITE_EMERGENCY_ADMIN_LAST_NAME:-Emergenza}"
VITE_EMERGENCY_ADMIN_GITHUB_TOKEN_VALUE="${VITE_EMERGENCY_ADMIN_GITHUB_TOKEN:-${MEDITRACE_GITHUB_PAT:-}}"

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by pwa/scripts/setup-production-deploy.sh
# Source: $ENV_FILE
# Do not commit this file.

VITE_BASE_URL=${VITE_BASE_URL_VALUE}
VITE_SUPABASE_URL=${VITE_SUPABASE_URL_VALUE}
VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY_VALUE}
VITE_SUPABASE_REDIRECT_TO=${VITE_SUPABASE_REDIRECT_TO_VALUE}

VITE_EMERGENCY_ADMIN_ENABLED=${VITE_EMERGENCY_ADMIN_ENABLED_VALUE}
VITE_EMERGENCY_ADMIN_USERNAME=${VITE_EMERGENCY_ADMIN_USERNAME_VALUE}
VITE_EMERGENCY_ADMIN_PASSWORD=${VITE_EMERGENCY_ADMIN_PASSWORD_VALUE}
VITE_EMERGENCY_ADMIN_EMAIL=${VITE_EMERGENCY_ADMIN_EMAIL_VALUE}
VITE_EMERGENCY_ADMIN_FIRST_NAME=${VITE_EMERGENCY_ADMIN_FIRST_NAME_VALUE}
VITE_EMERGENCY_ADMIN_LAST_NAME=${VITE_EMERGENCY_ADMIN_LAST_NAME_VALUE}
VITE_EMERGENCY_ADMIN_GITHUB_TOKEN=${VITE_EMERGENCY_ADMIN_GITHUB_TOKEN_VALUE}
EOF

echo "[ok] Wrote $OUTPUT_FILE"
echo "[info] Emergency admin enabled: $VITE_EMERGENCY_ADMIN_ENABLED_VALUE"

if [[ "$SET_GH" == "1" ]]; then
  require_cmd gh
  if ! gh auth status >/dev/null 2>&1; then
    echo "[error] gh CLI is not authenticated. Run: gh auth login"
    exit 1
  fi

  echo "[info] Syncing GitHub Variables/Secrets for production deploy..."
  set_repo_variable "VITE_BASE_URL" "$VITE_BASE_URL_VALUE"
  set_repo_variable "VITE_EMERGENCY_ADMIN_ENABLED" "$VITE_EMERGENCY_ADMIN_ENABLED_VALUE"
  set_repo_variable "VITE_EMERGENCY_ADMIN_USERNAME" "$VITE_EMERGENCY_ADMIN_USERNAME_VALUE"
  set_repo_variable "VITE_EMERGENCY_ADMIN_EMAIL" "$VITE_EMERGENCY_ADMIN_EMAIL_VALUE"
  set_repo_variable "VITE_EMERGENCY_ADMIN_FIRST_NAME" "$VITE_EMERGENCY_ADMIN_FIRST_NAME_VALUE"
  set_repo_variable "VITE_EMERGENCY_ADMIN_LAST_NAME" "$VITE_EMERGENCY_ADMIN_LAST_NAME_VALUE"
  set_repo_secret "VITE_EMERGENCY_ADMIN_PASSWORD" "$VITE_EMERGENCY_ADMIN_PASSWORD_VALUE"
  set_repo_secret "VITE_EMERGENCY_ADMIN_GITHUB_TOKEN" "$VITE_EMERGENCY_ADMIN_GITHUB_TOKEN_VALUE"
fi

if [[ "$RUN_BUILD" == "1" ]]; then
  require_cmd npm
  echo "[info] Running production build..."
  npm --prefix "$ROOT_DIR/pwa" run build
fi

if [[ "$TRIGGER_DEPLOY" == "1" ]]; then
  require_cmd gh
  if ! gh auth status >/dev/null 2>&1; then
    echo "[error] gh CLI is not authenticated. Run: gh auth login"
    exit 1
  fi
  echo "[info] Triggering workflow: Deploy PWA su GitHub Pages"
  gh workflow run ".github/workflows/deploy-pwa.yml"
  echo "[ok] Deploy workflow triggered"
fi

echo "[done] Production setup completed."
